import { Ionicons } from '@expo/vector-icons';
import { useNavigation, useRoute } from '@react-navigation/native';
import React, { useState } from 'react';
import { ActivityIndicator, Image, LayoutAnimation, Platform, ScrollView, StyleSheet, Text, TouchableOpacity, UIManager, View } from 'react-native';
import { Colors } from '../../constants/Colors';
import { GlobalStyles } from '../../constants/Styles';

if (Platform.OS === 'android') {
    if (UIManager.setLayoutAnimationEnabledExperimental) {
        UIManager.setLayoutAnimationEnabledExperimental(true);
    }
}

export default function BikeDetailsScreen() {
    const navigation = useNavigation<any>();
    const route = useRoute();
    const { bike } = route.params as { bike: any };

    const [specsExpanded, setSpecsExpanded] = useState(false);
    const [loadingSpecs, setLoadingSpecs] = useState(false);
    const [specsData, setSpecsData] = useState<any>(null);

    const toggleSpecs = () => {
        LayoutAnimation.configureNext(LayoutAnimation.Presets.easeInEaseOut);
        if (!specsExpanded) {
            setSpecsExpanded(true);
            setLoadingSpecs(true);
            // Simulate Gemini API call
            setTimeout(() => {
                setSpecsData({
                    engine: '1103cc Desmosedici Stradale V4',
                    power: '214 hp @ 13,000 rpm',
                    torque: '124.0 Nm @ 10,000 rpm',
                    weight: '175 kg (Dry)',
                    technology: 'Riding Modes, Power Modes, Cornering ABS EVO, Ducati Traction Control (DTC) EVO 2, Ducati Wheelie Control (DWC) EVO, Ducati Slide Control (DSC), Engine Brake Control (EBC) EVO, Auto tyre calibration',
                    description: 'The Panigale V4 replaces the iconic 1299 at the top of the Ducati supersport range, doing so by enhancing performance and ridability so that riders of all skill levels can enjoy unlimited fun and excitement.'
                });
                setLoadingSpecs(false);
            }, 1500);
        } else {
            setSpecsExpanded(false);
        }
    };

    return (
        <ScrollView style={GlobalStyles.container}>
            <Image source={{ uri: bike.image }} style={styles.heroImage} />

            <View style={GlobalStyles.screenContainer}>
                <Text style={styles.bikeName}>{bike.name}</Text>
                <Text style={styles.bikeYear}>{bike.year}</Text>

                <View style={styles.actionsContainer}>
                    <TouchableOpacity
                        style={styles.actionButton}
                        onPress={() => navigation.navigate('PartCategories', { bike })}
                    >
                        <Ionicons name="build" size={24} color={Colors.text} />
                        <Text style={styles.actionText}>Find Parts</Text>
                    </TouchableOpacity>

                    <TouchableOpacity
                        style={[styles.actionButton, specsExpanded && styles.activeActionButton]}
                        onPress={toggleSpecs}
                    >
                        <Ionicons name="sparkles" size={24} color={specsExpanded ? Colors.primary : Colors.text} />
                        <Text style={[styles.actionText, specsExpanded && { color: Colors.primary }]}>Specs</Text>
                    </TouchableOpacity>
                </View>

                {specsExpanded && (
                    <View style={styles.specsContainer}>
                        {loadingSpecs ? (
                            <View style={styles.loadingContainer}>
                                <ActivityIndicator size="small" color={Colors.primary} />
                                <Text style={styles.loadingText}>Asking Gemini...</Text>
                            </View>
                        ) : (
                            <View style={styles.specsContent}>
                                <View style={styles.aiHeader}>
                                    <Ionicons name="logo-google" size={16} color={Colors.textSecondary} />
                                    <Text style={styles.aiLabel}>Generated by Gemini</Text>
                                </View>

                                <Text style={styles.specsDescription}>{specsData.description}</Text>

                                <View style={styles.specRow}>
                                    <Text style={styles.specLabel}>Engine</Text>
                                    <Text style={styles.specValue}>{specsData.engine}</Text>
                                </View>
                                <View style={styles.specRow}>
                                    <Text style={styles.specLabel}>Power</Text>
                                    <Text style={styles.specValue}>{specsData.power}</Text>
                                </View>
                                <View style={styles.specRow}>
                                    <Text style={styles.specLabel}>Torque</Text>
                                    <Text style={styles.specValue}>{specsData.torque}</Text>
                                </View>
                                <View style={styles.specRow}>
                                    <Text style={styles.specLabel}>Weight</Text>
                                    <Text style={styles.specValue}>{specsData.weight}</Text>
                                </View>

                                <Text style={[styles.specLabel, { marginTop: 16, marginBottom: 8 }]}>Technology</Text>
                                <Text style={styles.specValue}>{specsData.technology}</Text>
                            </View>
                        )}
                    </View>
                )}

                <Text style={GlobalStyles.subtitle}>Recent Activity</Text>
                <View style={GlobalStyles.card}>
                    <Text style={{ color: Colors.textSecondary }}>No recent activity.</Text>
                </View>
            </View>
        </ScrollView>
    );
}

const styles = StyleSheet.create({
    heroImage: {
        width: '100%',
        height: 250,
    },
    bikeName: {
        fontSize: 28,
        fontWeight: 'bold',
        color: Colors.text,
        marginTop: 16,
    },
    bikeYear: {
        fontSize: 18,
        color: Colors.textSecondary,
        marginBottom: 24,
    },
    actionsContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 16,
    },
    actionButton: {
        backgroundColor: Colors.surface,
        flex: 1,
        marginHorizontal: 8,
        padding: 16,
        borderRadius: 12,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: Colors.border,
    },
    activeActionButton: {
        borderColor: Colors.primary,
        backgroundColor: '#1a0505',
    },
    actionText: {
        color: Colors.text,
        marginTop: 8,
        fontWeight: '600',
    },
    specsContainer: {
        backgroundColor: Colors.surface,
        borderRadius: 12,
        padding: 16,
        marginBottom: 32,
        borderWidth: 1,
        borderColor: Colors.border,
    },
    loadingContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        padding: 20,
        gap: 12,
    },
    loadingText: {
        color: Colors.textSecondary,
        fontSize: 14,
    },
    specsContent: {
        gap: 8,
    },
    aiHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        marginBottom: 12,
        opacity: 0.7,
    },
    aiLabel: {
        color: Colors.textSecondary,
        fontSize: 12,
        fontWeight: '500',
    },
    specsDescription: {
        color: Colors.text,
        fontSize: 14,
        lineHeight: 20,
        marginBottom: 16,
        fontStyle: 'italic',
    },
    specRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        borderBottomWidth: 1,
        borderBottomColor: Colors.border,
        paddingVertical: 8,
    },
    specLabel: {
        color: Colors.textSecondary,
        fontSize: 14,
    },
    specValue: {
        color: Colors.text,
        fontWeight: '600',
        fontSize: 14,
        flex: 1,
        textAlign: 'right',
        marginLeft: 16,
    },
});
